version: "3.7"
services:
  backend:
    image: heberf/finddev-backend-image
    container_name: finddev-backend-container
    restart: "always"
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/share/maven/backend
    volumes:
      - /finddev/backend:/usr/share/maven/backend
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    environment:
      SPRING_BOOT_ENVIRONMENT: prod
    command: mvn clean spring-boot:run
